services:
  - name: my-api
    env:
      - key: ENV
        value: production
    buildCommand: go build -o main
    startCommand: ./main
    scaling:
      mode: manual
      count: 2
    healthCheck:
      httpGet:
        path: /health
        port: 8080
        scheme: http
      initialDelaySeconds: 3
      periodSeconds: 10
    routes:
      - path: /*
        targetService: my-api
        type: http
    envVars:
      - name: JWT_SECRET
        value: "{{ env.JWT_SECRET }}"
