services:
  - type: service
    name: rest-api-portfolio
    buildCommand: go build -o main
    startCommand: ./main
    healthCheck:
      httpGet:
        path: /health
        port: 8080
        scheme: http
      initialDelaySeconds: 3
      periodSeconds: 10

